## Here will be stored numpy exercises. 
### Starting from here I will complete 20-45. Next markdown checkpoint will be used to indicate next 80-100 exercises.

In [1]:
import numpy as np
import pandas as pd

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [6]:
np.unravel_index(99, (6,7,8))
# 99 means the 99th element since arrays are 0-indexed
# unravel_index converts a 1D index to a tuple of coordinate indexes for a certain shape

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [8]:
np.tile(np.array([[0, 1], [1,0]]), (4,4))

# basically a block [0, 1], [1, 0] which has to be repeated 4 times along rows and 4 times along columns for a 8x8 matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [11]:
A = np.random.random((5,5))

A_norm = (A - A.min()) / (A.max() - A.min())

print(A_norm)

[[0.86876403 0.29189283 0.11170028 0.3300053  0.77944776]
 [0.         0.46954965 0.06601409 0.78394416 0.25489928]
 [0.12112292 0.863642   0.40369661 0.25152429 0.92097997]
 [0.04277374 0.98642993 0.60576246 0.71494945 0.21001164]
 [1.         0.6498924  0.36374349 0.86680959 0.23164214]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [14]:
# each field is a 8-bit unsigned integer 0 to 255 np.uint8
colors_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8), 
    ('blue', np.uint8),
    ('alpha', np.uint8)
])

pixel = np.array((255, 255, 0, 255),dtype = colors_dtype)

print(pixel['blue'])

0


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
A, B = np.ones((5, 3)), np.ones((3,2))

C = A @ B # or just np.dot(A,B)

print(C)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [16]:
A = np.arange(11)

A[(A > 3) & (A < 8)] *= -1 # condition > 3 AND < 8

print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

first line is a built-in python function which sums all the values till 5 starting from -1 -> -1 + 0 + 1 + 2 + 3 + 4 = 9
second line is a numpy library function that overrides the python's. argument -1 indicates the axis, so sum(5) along axis -1 is 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

everything is fine except the last one because it does the chained element-wise comparison for multi-element arrays

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. floating-point math that give NAN + runtime issue
2. gives a zero and a runtime issue since floors the floating math division
3. np.nan to integer gives a minimal representable 64-bit int, after converting to float it gives -9.22337204e+18

#### 29. How to round away from zero a float array ? (★☆☆)


In [18]:
z = np.array([-3.5, -2.1, -0.2, 0.2, 1.4, 4.8])

np.copysign(np.ceil(np.abs(z)), z)
# the idea is to take abs of all elements, round those up to the nearest int, copy the sign of b to magnitude a

array([-4., -3., -1.,  1.,  2.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [20]:
z1 = np.array([0, 1, 2, 3, 4, 5])
z2 = np.array([3, 4, 5, 6, 7, 8])

print(np.intersect1d(z1, z2)) # sorted unique values in both arrays

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [23]:
with np.errstate(all='ignore'):
    np.arange(3) / 0 # no warning with context manager

# or 

# global settings change (ignores all warnings for the script)
old_settings = np.seterr(all="ignore")
np.arange(3) / 0 # no warnings globally

# Reset settings back to default
_ = np.seterr(**old_settings)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

no because np.sqrt(-1) returns nan (only real numbers), while emath does the complex numbers (returns 1j or 0 + 1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [24]:
today = np.datetime64('today', 'D')
# today's date using 64-bit datetime representation in day units 'D'

yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2026-09-22
2026-09-21
2026-09-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [26]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]')) 
# range of daily dates 01-07 to 01-08 exclusive specifying [D] of datetime64

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [28]:
# init sample float arrays
A = np.ones(3, dtype=np.float64) * 4
B = np.ones(3, dtype=np.float64) * 2

# step by step operations
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

print(A)

[-12. -12. -12.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [31]:
z = np.random.uniform(0, 10, 10)

# 4 possible methods

m1 = np.floor(z) # truncate by flooring
m2 = np.trunc(z) # truncate in the direction of zeros
m3 = z.astype(int) # drops decimals by changing data type
m4 = z - z % 1 # substract fractional remainder

print(m1, m2, m3, m4, sep='\n')

[1. 2. 6. 3. 9. 5. 2. 4. 1. 6.]
[1. 2. 6. 3. 9. 5. 2. 4. 1. 6.]
[1 2 6 3 9 5 2 4 1 6]
[1. 2. 6. 3. 9. 5. 2. 4. 1. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [32]:
z = np.zeros((5,5)) + np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def int_generator():
    for x in range(10):
        yield x

# fromiter directly constructs the array from the iterable
z = np.fromiter(int_generator(), dtype = int, count = 10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [37]:
z = np.linspace(0, 1, 11, endpoint=False)[1:]
# np.linspace(start, stop, num) with endpoint=False creates 11 points starting at 0.
# slicing [1:] drops the 0 and gives 10 values only between (0, 1).
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)


In [40]:
z = np.random.random(10)

z.sort() # in place sorting just like in casual python
z

array([0.00589534, 0.15524236, 0.16072178, 0.18766566, 0.21152104,
       0.30020981, 0.63489585, 0.72058796, 0.77973232, 0.84846646])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [50]:
z = np.arange(10)

fast_sum = sum(z)
# it avoids the wrapper from python to c which numpy does by validatying axes, handling data types

fast_sum

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [47]:
A, B = np.random.randint(0,2,5), np.random.randint(0,2,5)

print(np.array_equal(A,B))
print(np.allclose(A, B))

# we get false since the random seed is not specified

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [48]:
x = np.eye(10)

x.flags.writeable = False 

x[0] = 10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [52]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
# generated 10x2 matrix with random points [0;1] and defined the axes
r = np.hypot(x,y) # sqrt(x^2 + y^2) radial distance

theta = np.arctan2(y, x) # theta angle

np.column_stack((r, theta)) #combined

array([[0.65711533, 0.92141622],
       [1.17915008, 0.9477088 ],
       [1.30691723, 0.72919904],
       [0.40790051, 0.86055398],
       [0.72319774, 0.00612371],
       [0.83944908, 1.55381501],
       [0.69663306, 0.5649469 ],
       [0.21791041, 0.32369572],
       [1.26784987, 0.72405143],
       [0.54371899, 0.7816848 ]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [54]:
vec = np.random.random(10)
print(vec)
print('*' * 10)
vec[vec.argmax()] = 0

print(vec)

[0.41255224 0.21063812 0.74553979 0.28927569 0.48556733 0.88947134
 0.69777149 0.52324417 0.70402377 0.22891218]
**********
[0.41255224 0.21063812 0.74553979 0.28927569 0.48556733 0.
 0.69777149 0.52324417 0.70402377 0.22891218]


## Here we got to the checkpoint: 80-100 exercises