## Here will be stored numpy exercises. 
### Starting from here I will complete 20-45. Next markdown checkpoint will be used to indicate next 80-100 exercises.

In [1]:
import numpy as np
import pandas as pd

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [6]:
np.unravel_index(99, (6,7,8))
# 99 means the 99th element since arrays are 0-indexed
# unravel_index converts a 1D index to a tuple of coordinate indexes for a certain shape

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [8]:
np.tile(np.array([[0, 1], [1,0]]), (4,4))

# basically a block [0, 1], [1, 0] which has to be repeated 4 times along rows and 4 times along columns for a 8x8 matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [11]:
A = np.random.random((5,5))

A_norm = (A - A.min()) / (A.max() - A.min())

print(A_norm)

[[0.86876403 0.29189283 0.11170028 0.3300053  0.77944776]
 [0.         0.46954965 0.06601409 0.78394416 0.25489928]
 [0.12112292 0.863642   0.40369661 0.25152429 0.92097997]
 [0.04277374 0.98642993 0.60576246 0.71494945 0.21001164]
 [1.         0.6498924  0.36374349 0.86680959 0.23164214]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [14]:
# each field is a 8-bit unsigned integer 0 to 255 np.uint8
colors_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8), 
    ('blue', np.uint8),
    ('alpha', np.uint8)
])

pixel = np.array((255, 255, 0, 255),dtype = colors_dtype)

print(pixel['blue'])

0


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [13]:
A, B = np.ones((5, 3)), np.ones((3,2))

C = A @ B # or just np.dot(A,B)

print(C)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [16]:
A = np.arange(11)

A[(A > 3) & (A < 8)] *= -1 # condition > 3 AND < 8

print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

first line is a built-in python function which sums all the values till 5 starting from -1 -> -1 + 0 + 1 + 2 + 3 + 4 = 9
second line is a numpy library function that overrides the python's. argument -1 indicates the axis, so sum(5) along axis -1 is 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

everything is fine except the last one because it does the chained element-wise comparison for multi-element arrays

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. floating-point math that give NAN + runtime issue
2. gives a zero and a runtime issue since floors the floating math division
3. np.nan to integer gives a minimal representable 64-bit int, after converting to float it gives -9.22337204e+18

#### 29. How to round away from zero a float array ? (★☆☆)


In [18]:
z = np.array([-3.5, -2.1, -0.2, 0.2, 1.4, 4.8])

np.copysign(np.ceil(np.abs(z)), z)
# the idea is to take abs of all elements, round those up to the nearest int, copy the sign of b to magnitude a

array([-4., -3., -1.,  1.,  2.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
z1 = np.array([0, 1, 2, 3, 4, 5])
z2 = np.array([3, 4, 5, 6, 7, 8])

print(np.intersect1d(z1, z2)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)