## Here will be stored numpy exercises. 
### Starting from here I will complete 20-45. Next markdown checkpoint will be used to indicate next 80-100 exercises.

In [100]:
import numpy as np
import pandas as pd

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [101]:
np.unravel_index(99, (6,7,8))
# 99 means the 99th element since arrays are 0-indexed
# unravel_index converts a 1D index to a tuple of coordinate indexes for a certain shape

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [102]:
np.tile(np.array([[0, 1], [1,0]]), (4,4))

# basically a block [0, 1], [1, 0] which has to be repeated 4 times along rows and 4 times along columns for a 8x8 matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [103]:
A = np.random.random((5,5))

A_norm = (A - A.min()) / (A.max() - A.min())

print(A_norm)

[[0.76871749 0.92606967 0.08956042 0.56000856 0.26571462]
 [0.06178041 0.18623901 0.59002979 1.         0.71308674]
 [0.08899757 0.74856876 0.99310824 0.10519564 0.        ]
 [0.2061772  0.92670798 0.73992581 0.17294899 0.6930101 ]
 [0.93546941 0.75136827 0.69940484 0.38842077 0.17295213]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [104]:
# each field is a 8-bit unsigned integer 0 to 255 np.uint8
colors_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8), 
    ('blue', np.uint8),
    ('alpha', np.uint8)
])

pixel = np.array((255, 255, 0, 255),dtype = colors_dtype)

print(pixel['blue'])

0


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [105]:
A, B = np.ones((5, 3)), np.ones((3,2))

C = A @ B # or just np.dot(A,B)

print(C)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [106]:
A = np.arange(11)

A[(A > 3) & (A < 8)] *= -1 # condition > 3 AND < 8

print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

first line is a built-in python function which sums all the values till 5 starting from -1 -> -1 + 0 + 1 + 2 + 3 + 4 = 9
second line is a numpy library function that overrides the python's. argument -1 indicates the axis, so sum(5) along axis -1 is 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

everything is fine except the last one because it does the chained element-wise comparison for multi-element arrays

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. floating-point math that give NAN + runtime issue
2. gives a zero and a runtime issue since floors the floating math division
3. np.nan to integer gives a minimal representable 64-bit int, after converting to float it gives -9.22337204e+18

#### 29. How to round away from zero a float array ? (★☆☆)


In [107]:
z = np.array([-3.5, -2.1, -0.2, 0.2, 1.4, 4.8])

np.copysign(np.ceil(np.abs(z)), z)
# the idea is to take abs of all elements, round those up to the nearest int, copy the sign of b to magnitude a

array([-4., -3., -1.,  1.,  2.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [108]:
z1 = np.array([0, 1, 2, 3, 4, 5])
z2 = np.array([3, 4, 5, 6, 7, 8])

print(np.intersect1d(z1, z2)) # sorted unique values in both arrays

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [109]:
with np.errstate(all='ignore'):
    np.arange(3) / 0 # no warning with context manager

# or 

# global settings change (ignores all warnings for the script)
old_settings = np.seterr(all="ignore")
np.arange(3) / 0 # no warnings globally

# Reset settings back to default
_ = np.seterr(**old_settings)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

no because np.sqrt(-1) returns nan (only real numbers), while emath does the complex numbers (returns 1j or 0 + 1j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [110]:
today = np.datetime64('today', 'D')
# today's date using 64-bit datetime representation in day units 'D'

yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2026-09-23
2026-09-22
2026-09-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [111]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]')) 
# range of daily dates 01-07 to 01-08 exclusive specifying [D] of datetime64

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [112]:
# init sample float arrays
A = np.ones(3, dtype=np.float64) * 4
B = np.ones(3, dtype=np.float64) * 2

# step by step operations
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

print(A)

[-12. -12. -12.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [113]:
z = np.random.uniform(0, 10, 10)

# 4 possible methods

m1 = np.floor(z) # truncate by flooring
m2 = np.trunc(z) # truncate in the direction of zeros
m3 = z.astype(int) # drops decimals by changing data type
m4 = z - z % 1 # substract fractional remainder

print(m1, m2, m3, m4, sep='\n')

[6. 8. 2. 1. 8. 3. 6. 4. 5. 9.]
[6. 8. 2. 1. 8. 3. 6. 4. 5. 9.]
[6 8 2 1 8 3 6 4 5 9]
[6. 8. 2. 1. 8. 3. 6. 4. 5. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [114]:
z = np.zeros((5,5)) + np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [115]:
def int_generator():
    for x in range(10):
        yield x

# fromiter directly constructs the array from the iterable
z = np.fromiter(int_generator(), dtype = int, count = 10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [116]:
z = np.linspace(0, 1, 11, endpoint=False)[1:]
# np.linspace(start, stop, num) with endpoint=False creates 11 points starting at 0.
# slicing [1:] drops the 0 and gives 10 values only between (0, 1).
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)


In [117]:
z = np.random.random(10)

z.sort() # in place sorting just like in casual python
z

array([0.01872441, 0.09217226, 0.14633574, 0.17915544, 0.24430585,
       0.25175894, 0.25643367, 0.83795438, 0.86378643, 0.88705843])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [118]:
z = np.arange(10)

fast_sum = sum(z)
# it avoids the wrapper from python to c which numpy does by validatying axes, handling data types

fast_sum

np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [119]:
A, B = np.random.randint(0,2,5), np.random.randint(0,2,5)

print(np.array_equal(A,B))
print(np.allclose(A, B))

# we get false since the random seed is not specified

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [120]:
x = np.eye(10)

x.flags.writeable = False 

x[0] = 10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [121]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
# generated 10x2 matrix with random points [0;1] and defined the axes
r = np.hypot(x,y) # sqrt(x^2 + y^2) radial distance

theta = np.arctan2(y, x) # theta angle

np.column_stack((r, theta)) #combined

array([[0.89106664, 1.11217766],
       [0.91032501, 0.55523268],
       [0.60116129, 0.0304326 ],
       [0.73467532, 0.07060994],
       [0.73330508, 0.94680888],
       [0.94394045, 1.33415199],
       [0.95962925, 1.07956802],
       [0.77266724, 0.88307957],
       [0.80160436, 0.60365663],
       [0.56250516, 1.03141592]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [122]:
vec = np.random.random(10)
print(vec)
print('*' * 10)
vec[vec.argmax()] = 0

print(vec)

[0.05974063 0.63648964 0.63411482 0.53497255 0.02846938 0.51343251
 0.0727798  0.57712191 0.49659323 0.30369856]
**********
[0.05974063 0.         0.63411482 0.53497255 0.02846938 0.51343251
 0.0727798  0.57712191 0.49659323 0.30369856]


## Here we got to the checkpoint: 80-100 exercises

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [123]:
def extract_centered_subpart(arr, shape, center, fill=0):
    # extract the subpart with the specified shape, 
    # centered with "center" and fills with "fill" if it is out of bounds
    
    arr = np.asarray(arr)
    shape = np.asarray(shape)
    center = np.asarray(center)

    # calculate the bounds relative to the center
    half_shape = shape // 2
    start = center - half_shape
    end = start + shape
    
    # calculate how much we should extend the array (padding) from each side
    pad_before = np.maximum(0, -start)
    pad_after = np.maximum(0, end - arr.shape)

    # safe bounds to slice from initiall arr
    src_start = np.maximum(0, start)
    src_end = np.maximum(arr.shape, end)

    # slicing
    slices = tuple(slice(s, e) for s, e in zip(src_start, src_end))
    cropped = arr[slices]

    # add the padding if out of bounds
    pad_width = list(zip(pad_before, pad_after))

    return np.pad(cropped, pad_width, mode = 'constant', constant_values = fill)
    

In [124]:
arr = np.arange(25).reshape(5, 5)

res = extract_centered_subpart(arr, shape=(3,3), center=(0,0), fill = -1)

res

array([[-1, -1, -1, -1, -1, -1],
       [-1,  0,  1,  2,  3,  4],
       [-1,  5,  6,  7,  8,  9],
       [-1, 10, 11, 12, 13, 14],
       [-1, 15, 16, 17, 18, 19],
       [-1, 20, 21, 22, 23, 24]])

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


In [125]:
arr =  np.arange(1, 15)
arr_sliding = np.lib.stride_tricks.sliding_window_view(arr, window_shape = 4)

arr_sliding

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)


In [126]:
x = np.random.uniform(0, 1, (4, 4))

rank = np.linalg.matrix_rank(x)

rank

np.int64(4)

#### 83. How to find the most frequent value in an array?

In [127]:
x = np.random.randint(0, 10, 50)

freq = np.bincount(x).argmax() # counts occurences of non-neg ints

print(x)
print(freq)

[9 3 7 0 1 2 6 3 3 7 1 4 1 1 1 2 6 7 6 7 6 8 2 7 9 9 7 1 7 9 3 1 6 8 2 0 9
 7 8 5 3 7 2 4 5 9 7 8 0 0]
7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [128]:
z = np.random.randint(0, 10, (10, 10))

blocks = np.lib.stride_tricks.sliding_window_view(z, (3,3))

# sliding_window_view creates non-copying views across specified dimensions

blocks.shape

(8, 8, 3, 3)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [129]:
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

def symmetric_matrix(dim, value=0):
    return np.full((dim, dim), value).view(SymmetricArray)

S = symmetric_matrix(4, 0)
S[0, 3] = 42
print(S)
print(S[3, 0] == S[0,3])

[[ 0  0  0 42]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [42  0  0  0]]
True


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


In [130]:
p, n = 10, 3

mat = np.ones((p, n, n))

vec = np.ones((p, n, 1))

# 'pij,pjk->ik' multiplies matching p index matrices/vectors and sums across p
res = np.einsum('pij, pjk -> ik', mat, vec)
print(res.shape)

(3, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [131]:
z = np.ones((16,16))

block_shape = (4, 4)

s = z.reshape(16//4, 4, 16//4, 4).sum(axis=(1,3))
print(s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)


In [132]:
def game_of_life(grid):
    # count 8 live neighbors by summing shifted slices of the grid
    neighbors = (
        grid[:-2, :-2] + grid[:-2, 1:-1] + grid[:-2, 2:] +
        grid[1:-1, :-2]                  + grid[1:-1, 2:] +
        grid[2:,   :-2] + grid[2:,   1:-1] + grid[2:,   2:]
    )
    
    # Extract interior region (since edges lack full neighbor count)
    interior = grid[1:-1, 1:-1]
    
    # any live cell with 2 or 3 neighbors survives.
    # any dead cell with exactly 3 neighbors becomes a live cell.
    birth = (neighbors == 3) & (interior == 0)
    survive = ((neighbors == 2) | (neighbors == 3)) & (interior == 1)
    
    # update interior
    grid[1:-1, 1:-1] = 0
    grid[1:-1, 1:-1][birth | survive] = 1
    
    return grid

Z = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]
])

Z = game_of_life(Z)
print(Z)

[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [133]:
z = np.array([1, 8, 3, 10, 2, 9, 7, 4, 5, 6])
n = 3

# np.argpartition places top n elements at the end without full sorting

indices = np.argpartition(z, -n)[-n:]
top_n = z[indices[np.argsort(-z[indices])]]

print(top_n)

[10  9  8]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [134]:
def cartesian_product(*arrays):
    # generates cartesian product with indexing = 'ij' generates multidimensional grids
    grid = np.meshgrid(*arrays, indexing='ij')
    # stack and reshape into n x m matrix
    return np.stack(grid, axis = -1).reshape(-1, len(arrays))

v1= [1,2]
v2 = [3,4]
v3 = [5,6]

cartesian_product(v1, v2, v3)

array([[1, 3, 5],
       [1, 3, 6],
       [1, 4, 5],
       [1, 4, 6],
       [2, 3, 5],
       [2, 3, 6],
       [2, 4, 5],
       [2, 4, 6]])

#### 91. How to create a record array from a regular array? (★★★)

In [135]:
Z = np.array([("Alice", 25, 55.5), ("Bob", 30, 85.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

R = np.rec.array(Z) # convert to recarray for attribute-based field access (e.g., R.name)

R.name # access fields as attributes

array(['Alice', 'Bob'], dtype='<U10')

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [136]:
z = np.random.rand(10000)

res1 = z ** 3

res2 = z * z * z

res3 = np.power(z, 3)

res4 = np.einsum('i, i, i -> i', z, z, z)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain at least one element of each row of B regardless of the order of the elements in B?


In [137]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 4, 7], 
              [2, 5, 8], [3, 6, 9], [1, 5, 9], [2, 4, 8]])
B = np.array([[1, 2], [5, 6]])


# expand dimensions to compare each row of A against each row of B element-wise
# A[:, None, :, None] -> (8, 1, 3, 1)
# B[None, :, None, :] -> (1, 2, 1, 2)
matches = (A[:, None, :, None] == B[None, :, None, :])

# check if at least one match exists per row of B (axis=(2,3)), then for all rows of B (axis=1)
valid_rows = np.all(np.any(matches, axis=(2,3)), axis = 1)

A[valid_rows]

array([[2, 5, 8],
       [1, 5, 9]])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [138]:
z = np.random.randint(0, 3, (10, 3))

all_equal = np.all(z == z[:, [0]], axis = 1)

unequal_rows = z[~all_equal]

unequal_rows

array([[1, 0, 1],
       [0, 2, 0],
       [0, 1, 1],
       [1, 2, 0],
       [1, 0, 0],
       [0, 1, 2],
       [0, 0, 1],
       [2, 1, 1],
       [0, 1, 1]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)


In [139]:
vec = np.array([0, 1, 2, 7, 15, 255], dtype=np.uint8)

# unpack 8 bits for each integer along axis 1
binary_matrix = np.unpackbits(vec[:, None], axis = 1)

binary_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)


In [140]:
z = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9]
])
np.unique(z, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [146]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

inner = np.einsum('i, i -> ', A, B) # np.inner(A,B) or np.dot(A, B)

outer = np.einsum('i,j -> ij', A, B) # same as np.outer(A, B)

total_sum = np.einsum('i->', A) # same as np.sum(A)

mul = np.einsum('i, i -> i', A, B) # same as A * B

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [147]:
# defined paths
X = np.array([0, 1, 2, 4, 7, 10])
Y = np.array([0, 1, 1, 3, 3, 5])

# cumulative path distance
dx = np.diff(X)
dy = np.diff(Y)
segment_lengths = np.hypot(dx, dy)
cumulative_dist = np.insert(np.cumsum(segment_lengths), 0, 0)

# equidistant target distances
num_samples = 10
target_dist = np.linspace(0, cumulative_dist[-1], num_samples)

# interpolate X and Y along the cumulative path length
X_sampled = np.interp(target_dist, cumulative_dist, X)
Y_sampled = np.interp(target_dist, cumulative_dist, Y)

path_sampled = np.column_stack((X_sampled, Y_sampled))
path_sampled

array([[ 0.        ,  0.        ],
       [ 0.93088188,  0.93088188],
       [ 2.15465697,  1.15465697],
       [ 3.08553885,  2.08553885],
       [ 4.02322241,  3.        ],
       [ 5.33968818,  3.        ],
       [ 6.65615395,  3.        ],
       [ 7.80926853,  3.53951235],
       [ 8.90463427,  4.26975618],
       [10.        ,  5.        ]])

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [148]:
X = np.array([[1, 2, 2], [0, 5, 0], [2.5, 2.5, 0], [1, 1, 3]])

n = 5

# all elements in row are integers
is_integer = np.all(np.mod(X, 1) == 0, axis = 1)

# row sum equals degree n
sums_to_n = (np.sum(X, axis=1) == n)

valid_rows = X[is_integer & sums_to_n]
valid_rows

array([[1., 2., 2.],
       [0., 5., 0.],
       [1., 1., 3.]])


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [149]:
X = np.random.normal(loc = 10.0, scale = 2.0, size = 100)

n_bootstraps = 1000
# resample elements with replacement (random indices of shape n_bootstraps x len(X))
bootstrap_indices = np.random.randint(0, len(X), size=(n_bootstraps, len(X)))
bootstrap_samples = X[bootstrap_indices]

# mean for each bootstrap sample along axis 1
bootstrap_means = np.mean(bootstrap_samples, axis = 1)

# for 95% confidence interval i take 2.5% from each side (lower and upper)
ci_lower = np.percentile(bootstrap_means, 2.5)
ci_upper = np.percentile(bootstrap_means, 97.5)

print(np.mean(X))
print(ci_lower.round(3), ci_upper.round(3))


10.160188797036062
9.689 10.602


### finish!!!